
name: Build with different JDKs

on: push

permissions:
    id-token: write
    contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ '8', '11', '16', '17' ]
        os: [ubuntu-latest, windows-latest]
    name: Java ${{ matrix.Java }} build on ${{ matrix.os }}

    steps:    
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build project
      run: ./gradlew clean installDist
    - name: Run cli
      run: ./build/install/aws-codeguru-cli/bin/aws-codeguru-cli

