# Created using https://github.com/aws-samples/aws-codeguru-reviewer-cicd-cdk-sample
name: Self-test and release

on: [push, pull_request, workflow_dispatch]

permissions:
    id-token: write
    contents: read

jobs:
  SelfTest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Self Test on ${{ matrix.os }}
    steps:    
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      run: ./gradlew clean installDist distZip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      continue-on-error: true
      id: iam-role
      with:
        role-to-assume: arn:aws:iam::048169001733:role/GuruGitHubCICDRole
        aws-region: us-west-2


    - name: Checkout Test Data
      if: steps.iam-role.outcome == 'success'
      uses: actions/checkout@master
      with:
        repository: aws-samples/amazon-codeguru-samples
        path: ./amazon-codeguru-samples

    - name: Build Test Project
      if: steps.iam-role.outcome == 'success'
      run: |
        cd amazon-codeguru-samples
        ./gradlew
        cd ..

    - name: Self Test
      if: steps.iam-role.outcome == 'success'
      run: |
        ./build/install/aws-codeguru-cli/bin/aws-codeguru-cli --region us-west-2 -r amazon-codeguru-samples -s amazon-codeguru-samples/src/main/java -b amazon-codeguru-samples/build/libs --no-prompt
        cat code-guru/recommendations.json
        [[ $(grep "filePath" code-guru/recommendations.json | wc -l) -eq 12 ]] || { echo >&2 "Expected 12 recommendations."; exit 1; }

  PublishVersion:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build project
      run: ./gradlew clean installDist distZip

    - name: Get Release Version
      run: |
        echo "::set-output name=TAG_NAME::$(./gradlew properties -q | grep "version:" | awk '{print $2}')"
      id: version

    - name: Release
      if: steps.iam-role.outcome == 'success'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.version.outputs.TAG_NAME }}
        prerelease: false
        draft: false
        body: >
          Version ${{ steps.version.outputs.TAG_NAME }} of the AWS CodeGuru Reviewer CLI.
        files: |
          ./build/distributions/aws-codeguru-cli.zip
          LICENSE